Repository Software-Meister-High-School-Community/MOIZA-iOS, pull requests merged in 2022-02, with the labels that each got.

#15 모이자 Step 설계 (파라미터 작업x)
  Target/Source/Application/Step/MoizaStep.swift
Labels: 2️⃣Priority: Medium, ⚙ Setting

#13 🔀 :: 졸업생 인증 페이지
  Target/Source/Application/DI/Container/AppDI.swift
  Target/Source/Application/Flow/Flows/OnBoardingFlow.swift
  Target/Source/Application/Step/MoizaStep.swift
  Target/Source/Presentation/Scene/Auth/Common/View/MoizaRadioButton.swift
  Target/Source/Presentation/Scene/Auth/Common/View/NextButton.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Graduate/Auth/Reactor/GraduateAuthReactor.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Graduate/Auth/VC/GraduateAuthVC.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Graduate/File/Reactor/GraduateFileReactor.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Graduate/File/VC/GraduateFileVC.swift
  Target/Source/Presentation/Scene/Auth/SignUp/SignInSetUp/Reactor/SignUpSetUpReactor.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Success/Graduate/Reactor/GraduateSuccessReactor.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Success/Graduate/VC/GraduateSuccessVC.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Success/SignUp/Reactor/SignUpSuccessReactor.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Success/SignUp/VC/SignUpSuccessVC.swift
  Target/Support/Info.plist
Labels: 2️⃣Priority: Medium, ✨ Feature

#19 로그인 하기
  Target/Source/Application/DI/Container/AppDI.swift
  Target/Source/Application/Flow/Flows/OnBoardingFlow.swift
  Target/Source/Presentation/Scene/Auth/SignIn/Common/View/DivisionLine.swift
  Target/Source/Presentation/Scene/Auth/SignIn/Common/View/SignInTextField.swift
  Target/Source/Presentation/Scene/Auth/SignIn/Reactor/SignInReactor.swift
  Target/Source/Presentation/Scene/Auth/SignIn/VC/SignInVC.swift
  Target/Source/Presentation/Scene/OnBoarding/VC/OnBoardingVC.swift
  Target/Source/Presentation/Utils/Extensions/UIKit/UITextField/UITextFieldExt.swift
Labels: 1️⃣Priority: High, ✨ Feature

#21 IQKeyboardManager
  Podfile
  Podfile.lock
  Target/Source/Application/AppDelegate.swift
  Target/Source/Presentation/Base/baseVC.swift
  Target/Source/Presentation/Scene/Auth/SignUp/Info/VC/SignUpInfoVC.swift
  Target/Source/Presentation/Scene/Auth/SignUp/SignInSetUp/VC/SignUpSetUpVC.swift
  Target/Source/Presentation/Utils/Extensions/UIKit/UIViewController/UIViewControllerExt.swift
Labels: ⚙ Setting, 3️⃣Priority: Low

#22 🔀 :: Tabbar Setup
  Target/Source/Application/DI/Container/AppDI.swift
  Target/Source/Application/Flow/Flows/Main/Items/AlarmFlow.swift
  Target/Source/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Target/Source/Application/Flow/Flows/Main/Items/MyPageFlow.swift
  Target/Source/Application/Flow/Flows/Main/Items/PostListFlow.swift
  Target/Source/Application/Step/MoizaStep.swift
  Target/Source/Domain/Entities/Major.swift
  Target/Source/Presentation/Scene/Main/Items/Alarm/Reactor/AlarmReactor.swift
  Target/Source/Presentation/Scene/Main/Items/Alarm/VC/AlarmVC.swift
  Target/Source/Presentation/Scene/Main/Items/Home/Reactor/HomeReactor.swift
  Target/Source/Presentation/Scene/Main/Items/Home/VC/HomeVC.swift
  Target/Source/Presentation/Scene/Main/Items/MyPage/Reactor/MyPageReactor.swift
  Target/Source/Presentation/Scene/Main/Items/MyPage/VC/MyPageVC.swift
  Target/Source/Presentation/Scene/Main/Items/PostList/Category/Reactor/CategoryReactor.swift
  Target/Source/Presentation/Scene/Main/Items/PostList/Category/VC/CategoryVC.swift
  Target/Source/Presentation/Scene/Main/Items/PostList/PostList/Reactor/PostListReactor.swift
  Target/Source/Presentation/Scene/Main/Items/PostList/PostList/VC/PostListVC.swift
Labels: ⚙ Setting, 1️⃣Priority: High, ✨ Feature

#29 🔀 :: 라이브러리 추가
  Podfile
  Podfile.lock
Labels: ⚙ Setting, 3️⃣Priority: Low

#30 🔀 :: RealmSwift
  Derived/Sources/Assets+MOIZA.swift
  Podfile
  Podfile.lock
Labels: ⚙ Setting

#31 🔀 :: VHBoomMenuButton
  Podfile
  Podfile.lock
Labels: ⚙ Setting

#32 🔀 :: AppIcon 설정
  Target/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Target/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🌏 Deploy

#37 🔀 :: FCM Setting
  Target/Resource/GoogleService-Info.plist
  Target/Source/Application/AppDelegate.swift
Labels: ⚙ Setting, 🌏 Deploy
